#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "m15"
sudo scutil --set HostName "m15"
sudo scutil --set LocalHostName "m15"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "m15"

# Set "Use all F1, F2 as standard keys"
defaults write -g com.apple.keyboard.fnState -bool true

# Set dock on right hand side
defaults write com.apple.dock orientation right

# Make the caps lock key act as control
osascript ./macos/capslock-to-control.scpt


# When using Command key as Meta key on Emacs GUI version, Command-Ctrl-d (C-M-d)
# shortcut does not work unless the system wide OSX shortcut has been disabled
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 70 '<dict><key>enabled</key><false/></dict>'
