#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set "Use all F1, F2 as standard keys"
defaults write -g com.apple.keyboard.fnState -bool true

# Set dock on right hand side
defaults write com.apple.dock orientation right

# Make the caps lock key act as control
osascript ./osx/capslock-to-control.scpt