#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

# General aliases
alias 0='cd ~/0'
alias l='ls -lha'
alias c='clear'
alias untar='tar -xzvpf'
alias mktar='tar -czvpf'

# Emacs aliases
alias e='emacsclient -t'
alias et='emacsclient -t'
alias ec='emacsclient -c'
alias vim='emacsclient -t'
alias vi='emacsclient -t'
alias el='/Applications/Emacs.app/Contents/MacOS/Emacs -q -l ~/.log.d/init.el'
alias er='emacsclient -e "(kill-emacs)" && emacs --daemon && emacsclient -c &'

# Git aliases
source ~/.dotfiles/git/aliases

# Maven aliases
source ~/.dotfiles/maven/aliases

# Project aliases
alias hibernate="source ~/.dotfiles/includes/hibernate.sh"
alias infinispan="source ~/.dotfiles/includes/infinispan.sh"
alias jdg="source ~/.dotfiles/includes/jdg.sh"

# Java aliases
alias dump-threads="~/.dotfiles/java/dump-threads.sh"
alias untilfail="~/.dotfiles/java/untilfail.sh"

# JBoss aliases
alias jboss-kill='pkill -9 -f ".*/java .* org.jboss.as.standalone .*" \
  || pkill -9 -f ".*/java .* org.jboss.as.process-controller .*"'

#
# Functions
#

# Find any file
function fnd {
  find . -iname "*${1}*"
}
